### ISSUE TITLE
Add bookmarklet icon

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/cozy-archives#19]
I think it's supposed to use the favicon, but need to test.

**Comment by jojorb** [comment]
yep there is no icon yet and i've got this error:
edit: move comment to #20 

> `GET https://user_name.cozycloud.cc/apps/frost/#/bm.js [HTTP/1.1 304 Not Modified 3432 ms]`
> `SyntaxError: expected expression, got '<'`

**Comment by y-lohse** [comment]
Actually it looks like having a bookmarklet icon involves significant effort and doesn't really work, so let's forget about this.
