### ISSUE TITLE
Stronger bookmarklet generation

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/cozy-archives#20]
When the bookmarklet is generated, a `#` may be inserted at the end, which will break the loading.
Also on instancs hosted by cozy, it seems that the url is not the right one..?

**Comment by jojorb** [comment]
yes if not here the console message:
`GET https://user_name.cozycloud.cc/apps/frost/#/bm.js [HTTP/1.1 304 Not Modified 3432 ms]`
`SyntaxError: expected expression, got '<'`
and nothing happend
