### ISSUE TITLE
User agent setting?

### ISSUE THREAD

**Issue by stueja** [y-lohse/cozy-archives#26]
I found that, using cozy-frost, some webpages are stored, for others, the result of HTTP 403/unauthorized is being stored.
I assume it might be an issue with the user agent. 
Is there a possibility to change the user agent string, and if so, where?

**Comment by y-lohse** [comment]
That's a good point. I guess [this problem](https://forum.cozy.io/t/frost-application/2123/54) is probably user agent related too. We should probably spoof a user agent.

If possible at all, I gues the option would be set around [here](https://github.com/y-lohse/cozy-frost/blob/master/server/controllers/snapshots.js#L95). However [website-scraper](https://www.npmjs.com/package/website-scraper) doesn't seem to have an option for a user agent. Maybe we need to use a fork or a completely different lib from scraping.

Would you be interested in taking a look at this?

**Comment by y-lohse** [comment]
I think the user agent can actually be sent by website scrapper after all; by passing the `request` option, we could set the [header for request](https://github.com/request/request#requestoptions-callback) and pretend to me firefox or whatever.
